"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const getAllUsers_1 = __importDefault(require("./getAllUsers"));
const changeRole_1 = __importDefault(require("./changeRole"));
const changePremium_1 = __importDefault(require("./changePremium"));
const getUserById_1 = __importDefault(require("./getUserById"));
const sendEmail_1 = __importDefault(require("./sendEmail"));
const deleteUserReview_1 = __importDefault(require("./deleteUserReview"));
const banUser_1 = __importDefault(require("./banUser"));
const deleteUser_1 = __importDefault(require("./deleteUser"));
const closeReview_1 = __importDefault(require("./closeReview"));
router.use("/getAllUsers", getAllUsers_1.default);
router.use("/changeRole", changeRole_1.default);
router.use("/changePremium", changePremium_1.default);
router.use("/getUserById", getUserById_1.default);
router.use("/sendEmail", sendEmail_1.default);
router.use("/deleteUserReview", deleteUserReview_1.default);
router.use("/banUser", banUser_1.default);
router.use("/deleteUser", deleteUser_1.default);
router.use("/closeReview", closeReview_1.default);
exports.default = router;
